[phases.setup]
nixPkgs = ['php', 'phpExtensions.curl', 'phpExtensions.mbstring', 'phpExtensions.pdo_mysql', 'composer']

[phases.build]
cmd = "composer install --optimize-autoloader --no-dev"

[phases.start]
cmd = "php artisan migrate --force && php artisan optimize && php artisan serve --host 0.0.0.0 --port $PORT"
