services:
  - type: web
    name: sekolyapp
    env: docker
    buildCommand: "./vendor/bin/heroku-php-apache2 public/"
    startCommand: "php artisan serve --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: APP_KEY
        generateValue: true
    buildpacks:
      - https://github.com/heroku/heroku-buildpack-php
